name: CI_develope
on:
  push:
    branches:
      - develope
jobs:
    # unit-test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Set RELEASE_TAG output
    #           id: set_release_tag
    #           run: echo "::set-output name=RELEASE_TAG::${{ github.event.release.tag_name }}"  
    #         - name: Setup PHP
    #           uses: shivammathur/setup-php@v2
    #           with:
    #             php-version: '8.2'
    #             extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
    #             coverage: none
    #         - name: Run composer install
    #           run: composer install -n --prefer-dist
    #         - name: Prepare Laravel Application
    #           run: |
    #             php artisan key:generate --env=testing
    #         - name: Run tests
    #           run: php artisan test --env=testing
    continuous-integration:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/develope'
      # needs: [unit-test]
      timeout-minutes: 15
      steps:
          - name: Check out code
            uses: actions/checkout@v3

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2.2.0

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2.9.1

          - name: Login in to Docker Hub -
            uses: docker/login-action@v2.1.0
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build and push to Docker Hub
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                #athenadean/pure-land-temple 這是  docekr account 帳號/docker hub repo名稱  
                tags: athena0080/athena-web:latest
                cach-from: type=gha
                cach-to: type=gha,mode=max